# Generated by Django 5.2.9 on 2026-03-31 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patientprofile_assigned_agent'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='patients.subscription'),
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Numéro de visite du cycle'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('absent', 'Patient absent'), ('rescheduled', 'Reportée'), ('cancelled', 'Annulé')], default='pending', max_length=20),
        ),
    ]
