# Generated by Django 5.2.9 on 2026-04-02 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_visit_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitPreScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fasting_status', models.CharField(choices=[('yes', 'À jeun'), ('no', 'Pas à jeun'), ('unknown', 'Ne sait pas')], max_length=10)),
                ('has_pain', models.BooleanField()),
                ('pain_description', models.TextField(blank=True)),
                ('takes_medications', models.BooleanField()),
                ('medications_taken_status', models.CharField(choices=[('na', 'Sans objet'), ('yes', 'Oui, pris comme prévu'), ('no', 'Non'), ('partial', 'Partiellement')], max_length=10)),
                ('medication_names', models.TextField(blank=True)),
                ('extra_notes', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pre_screening', to='visits.visit')),
            ],
            options={
                'db_table': 'visit_pre_screenings',
            },
        ),
    ]
