# Generated by Django 5.2.9 on 2026-04-07 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(blank=True, default='', max_length=150)),
                ('donor_email', models.EmailField(blank=True, default='', max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone_number', models.CharField(max_length=20)),
                ('payment_method', models.CharField(choices=[('FLOOZ', 'FLOOZ'), ('TMONEY', 'TMONEY')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Terminee'), ('failed', 'Echouee'), ('refunded', 'Remboursee')], default='pending', max_length=20)),
                ('identifier', models.CharField(max_length=100, unique=True)),
                ('tx_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'donation_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaygateDonationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_reference', models.CharField(max_length=100, unique=True)),
                ('identifier', models.CharField(max_length=100, unique=True)),
                ('payment_reference', models.CharField(blank=True, default='', max_length=100)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, default='', max_length=20)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paygate_status', to='payments.donationtransaction')),
            ],
            options={
                'db_table': 'paygate_donation_statuses',
                'ordering': ['-created_at'],
            },
        ),
    ]
