# Generated by Django 5.2.9 on 2026-03-30 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'zones',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='agents/avatars/')),
                ('professional_id', models.CharField(max_length=100, unique=True)),
                ('specialization', models.CharField(max_length=200)),
                ('experience_years', models.IntegerField(default=0)),
                ('approval_status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('is_available', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agent_profiles',
            },
        ),
        migrations.CreateModel(
            name='AgentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('national_id', "Pièce d'identité nationale"), ('diploma', 'Diplôme'), ('license', 'Licence professionnelle'), ('other', 'Autre')], max_length=20)),
                ('file', models.FileField(upload_to='agents/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='agents.agentprofile')),
            ],
            options={
                'db_table': 'agent_documents',
            },
        ),
        migrations.CreateModel(
            name='AgentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='agents.agentprofile')),
            ],
            options={
                'db_table': 'agent_schedules',
                'unique_together': {('agent', 'day_of_week')},
            },
        ),
        migrations.CreateModel(
            name='AgentZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='agents.agentprofile')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='agents.zone')),
            ],
            options={
                'db_table': 'agent_zones',
                'unique_together': {('agent', 'zone')},
            },
        ),
    ]
