# Generated by Cursor on 2026-03-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Zone',
            new_name='ResidenceZone',
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='residence_zone',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='agents',
                to='agents.residencezone',
            ),
        ),
        migrations.DeleteModel(
            name='AgentZone',
        ),
    ]

