# Generated by Django 5.2.9 on 2026-03-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_residence_zone_and_agent_profile_residence_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprofile',
            name='professional_id',
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='profession',
            field=models.CharField(choices=[('nurse_general', 'Infirmier(ère) généraliste'), ('nurse_clinical', 'Infirmier(ère) clinicien(ne)'), ('nurse_icu', 'Infirmier(ère) aux soins intensifs'), ('nurse_emergency', 'Infirmier(ère) urgentiste'), ('nurse_psych', 'Infirmier(ère) en santé mentale'), ('nurse_pediatric', 'Infirmier(ère) pédiatrique'), ('nurse_community', 'Infirmier(ère) communautaire'), ('nurse_practitioner', 'Infirmier(ère) praticien(ne)'), ('nursing_assistant', 'Aide-soignant(e)'), ('nursing_assistant_psych', 'Aide-soignant(e) psychiatrique'), ('midwife', 'Sage-femme'), ('auxiliary_childcare', 'Auxiliaire de puériculture'), ('physiotherapist', 'Kinésithérapeute'), ('occupational_therapist', 'Ergothérapeute'), ('speech_therapist', 'Orthophoniste'), ('nutritionist', 'Diététicien(ne) / nutritionniste'), ('medical_doctor', 'Médecin'), ('psychologist', 'Psychologue'), ('social_worker', 'Assistant(e) social(e)'), ('medical_lab_tech', 'Technicien(ne) de laboratoire médical'), ('pharmacy_tech', 'Technicien(ne) en pharmacie'), ('paramedic', 'Ambulancier(ère) / aide médical urgent'), ('dentist', 'Chirurgien(ne)-dentiste'), ('medical_technician', 'Technicien(ne) médical(e)'), ('caregiver_elderly', 'Accompagnant(e) / auxiliaire de vie'), ('other', 'Autre')], default='other', max_length=40),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
