# Generated by Django 5.2.9 on 2026-04-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_agent_pending_zones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='coverage_zones',
            field=models.ManyToManyField(blank=True, help_text="Zones approuvées pour l'assignation (matching).", related_name='covering_agents', to='agents.residencezone'),
        ),
    ]
