# Generated by Django 5.2.9 on 2026-06-28 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_split_full_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_rejections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
