# Generated by Django 5.2.9 on 2026-06-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_agent_rejection_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('revision_required', 'Corrections demandées'), ('rejected', 'Rejeté')], default='pending', max_length=20),
        ),
    ]
