# Generated by Django 3.2.25 on 2026-06-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_revision_required_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='revision_notes',
            field=models.TextField(blank=True, default='', help_text="Réponse textuelle de l'agent aux demandes de l'administrateur."),
        ),
    ]
