# Generated by Django 5.2.9 on 2026-03-30 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0004_agent_coverage_zones'),
        ('patients', '0002_patient_zone_to_residence_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_agent_ids', models.JSONField(default=list)),
                ('current_index', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('assigned', 'Assigné'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_queues', to='patients.patientprofile')),
            ],
            options={
                'db_table': 'assignment_queues',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepté'), ('declined', 'Refusé'), ('expired', 'Expiré'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_requests', to='agents.agentprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_requests', to='patients.patientprofile')),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='matching.assignmentqueue')),
            ],
            options={
                'db_table': 'assignment_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
