# Generated by Django 5.2.9 on 2026-03-30 23:32

from django.db import migrations

DEFAULT_SETTINGS = [
    {
        'key': 'assignment_notice_duration',
        'value': '24 heures',
        'description': (
            'Durée indicative communiquée au patient lors de l\'inscription pour '
            'l\'assignation d\'un agent (ex: "24 heures", "48 heures").'
        ),
    },
    {
        'key': 'assignment_request_timeout_hours',
        'value': '6',
        'description': 'Délai (en heures) accordé à un agent pour répondre à une demande d\'assignation.',
    },
    {
        'key': 'matching_retry_delay_hours',
        'value': '6',
        'description': 'Délai (en heures) avant de relancer le matching si aucun agent n\'a accepté.',
    },
    {
        'key': 'matching_max_retries',
        'value': '3',
        'description': 'Nombre maximum de tentatives de matching avant d\'abandonner.',
    },
]


def seed_settings(apps, schema_editor):
    AdminSetting = apps.get_model('admin_api', 'AdminSetting')
    for s in DEFAULT_SETTINGS:
        AdminSetting.objects.get_or_create(key=s['key'], defaults={
            'value': s['value'],
            'description': s['description'],
        })


def unseed_settings(apps, schema_editor):
    AdminSetting = apps.get_model('admin_api', 'AdminSetting')
    keys = [s['key'] for s in DEFAULT_SETTINGS]
    AdminSetting.objects.filter(key__in=keys).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_settings, reverse_code=unseed_settings),
    ]

