# Generated by Cursor on 2026-03-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_residence_zone_and_agent_profile_residence_zone'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='zone',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='patients',
                to='agents.residencezone',
            ),
        ),
    ]

