# Generated by Django 5.2.9 on 2026-03-30 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agent_coverage_zones'),
        ('patients', '0002_patient_zone_to_residence_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='assigned_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patients', to='agents.agentprofile'),
        ),
    ]
